In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_columns', 100)

In [2]:
input_file = "raw/ContractNLI_reuben/train-00000-of-00001-d5675d98fde8c367.parquet"
df_short = pd.read_parquet(input_file)
df_short

,document_id,file_name,text,hypothesis_id,hypothesis,label,evidence_spans,evidence_texts
0,34,Annex E_Non-Disclosure and Confidentiality Agreement.pdf,NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT\nThis NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT ...,nda-11,Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confident...,notmentioned,[],[]
1,34,Annex E_Non-Disclosure and Confidentiality Agreement.pdf,NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT\nThis NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT ...,nda-16,Receiving Party shall destroy or return some Confidential Information upon the termination of Ag...,entailment,"[[5021, 5179], [5179, 5347]]","[5. All Confidential Information in any form and any medium, including all copies thereof, discl..."
2,34,Annex E_Non-Disclosure and Confidentiality Agreement.pdf,NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT\nThis NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT ...,nda-15,Agreement shall not grant Receiving Party any right to Confidential Information.,entailment,"[[4834, 5020]]","[4. Nothing in this Agreement is to be construed as granting the Recipient, by implication or ot..."
3,34,Annex E_Non-Disclosure and Confidentiality Agreement.pdf,NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT\nThis NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT ...,nda-10,Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.,entailment,"[[7292, 7645]]",[11. The Recipient shall not advertise or otherwise make public the fact that it has a confident...
4,34,Annex E_Non-Disclosure and Confidentiality Agreement.pdf,NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT\nThis NON-DISCLOSURE AND CONFIDENTIALITY AGREEMENT ...,nda-2,Confidential Information shall only include technical information.,notmentioned,[],[]
...,...,...,...,...,...,...,...,...
7186,624,1693664_0001193125-18-171470_d426098dex99d3.htm,Exhibit (d)(3)\nNON-DISCLOSURE AGREEMENT\nThis NON-DISCLOSURE AGREEMENT (“Agreement”) is being e...,nda-17,Receiving Party may create a copy of some Confidential Information in some circumstances.,notmentioned,[],[]
7187,624,1693664_0001193125-18-171470_d426098dex99d3.htm,Exhibit (d)(3)\nNON-DISCLOSURE AGREEMENT\nThis NON-DISCLOSURE AGREEMENT (“Agreement”) is being e...,nda-8,"Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regula...",entailment,"[[5776, 6200]]",[(c) If the Recipient or any of the Recipient’s Representatives is required by law or government...
7188,624,1693664_0001193125-18-171470_d426098dex99d3.htm,Exhibit (d)(3)\nNON-DISCLOSURE AGREEMENT\nThis NON-DISCLOSURE AGREEMENT (“Agreement”) is being e...,nda-13,Receiving Party may acquire information similar to Confidential Information from a third party.,entailment,"[[18317, 18398], [19109, 19498]]","[However, the Provider’s “Confidential Information” will not be deemed to include:, (iii) any in..."
7189,624,1693664_0001193125-18-171470_d426098dex99d3.htm,Exhibit (d)(3)\nNON-DISCLOSURE AGREEMENT\nThis NON-DISCLOSURE AGREEMENT (“Agreement”) is being e...,nda-5,Receiving Party may share some Confidential Information with some of Receiving Party's employees.,entailment,"[[4143, 4330], [4330, 4480], [19711, 19832], [19832, 19886], [19886, 20060]]","[(ii) subject to Section 4(b) below, the Recipient may disclose Confidential Information of the ..."
7190,624,1693664_0001193125-18-171470_d426098dex99d3.htm,Exhibit (d)(3)\nNON-DISCLOSURE AGREEMENT\nThis NON-DISCLOSURE AGREEMENT (“Agreement”) is being e...,nda-4,Receiving Party shall not use any Confidential Information for any purpose other than the purpos...,entailment,"[[1192, 1332], [1333, 1542], [2411, 2664]]",[Neither the Recipient nor any of the Recipient’s Representatives (as defined in Section 13 belo...

In [4]:
input_file = "raw/ContractNLI_reuben/test-00000-of-00001-762092f06e2d7b48.parquet"
df_short = pd.read_parquet(input_file)
print(df_short.shape)
print(df_short.hypothesis.value_counts())

(2091, 8)
hypothesis
Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information.                                                      123
Confidential Information may include verbally conveyed information.                                                                                                   123
Receiving Party may share some Confidential Information with some of Receiving Party's employees.                                                                     123
Receiving Party may acquire information similar to Confidential Information from a third party.                                                                       123
Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.    123
Receiving Party may create a copy of some Confidential Information in some circumstances.                                                                             123
Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).                            123
Receiving Party shall not solicit some of Disclosing Party's representatives.                                                                                         123
Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.                                            123
Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.                                                              123
Receiving Party may independently develop information similar to Confidential Information.                                                                            123
Some obligations of Agreement may survive termination of Agreement.                                                                                                   123
All Confidential Information shall be expressly identified by the Disclosing Party.                                                                                   123
Confidential Information shall only include technical information.                                                                                                    123
Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.                                                                                  123
Agreement shall not grant Receiving Party any right to Confidential Information.                                                                                      123
Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.                                               123
Name: count, dtype: int64

In [13]:
input_file = "raw/ContractNLI_reuben/validation-00000-of-00001-3714eab8cedda2e5.parquet"
df_short = pd.read_parquet(input_file)
print(df_short.shape)
print(df_short.hypothesis.value_counts())

(1037, 8)
hypothesis
Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information.                                                      61
Confidential Information may include verbally conveyed information.                                                                                                   61
Receiving Party may share some Confidential Information with some of Receiving Party's employees.                                                                     61
Receiving Party may acquire information similar to Confidential Information from a third party.                                                                       61
Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.    61
Receiving Party may create a copy of some Confidential Information in some circumstances.                                                                             61
Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).                            61
Receiving Party shall not solicit some of Disclosing Party's representatives.                                                                                         61
Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.                                            61
Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.                                                              61
Receiving Party may independently develop information similar to Confidential Information.                                                                            61
Some obligations of Agreement may survive termination of Agreement.                                                                                                   61
All Confidential Information shall be expressly identified by the Disclosing Party.                                                                                   61
Confidential Information shall only include technical information.                                                                                                    61
Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.                                                                                  61
Agreement shall not grant Receiving Party any right to Confidential Information.                                                                                      61
Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.                                               61
Name: count, dtype: int64

In [17]:
evidence = df_short.head(10)['evidence_texts']
for i, ev in enumerate(evidence):
    print(i)
    for j, sentence in enumerate(ev):
        print(f"  Sentence {j+1}: {sentence}")

0
1
  Sentence 1: 5. All Confidential Information in any form and any medium, including all copies thereof, disclosed to the Recipient shall be returned to UNHCR or destroyed:
  Sentence 2: (a) if a business relationship is not entered into with UNHCR on or before the date which is three (3) months after the date both Parties have signed the Agreement; or
2
  Sentence 1: 4. Nothing in this Agreement is to be construed as granting the Recipient, by implication or otherwise, any right whatsoever with respect to the Confidential Information or part thereof.
3
  Sentence 1: 11. The Recipient shall not advertise or otherwise make public the fact that it has a confidential relationship with UNHCR, nor shall the Recipient, in any manner whatsoever use the name, emblem, or official seal of the United Nations or UNHCR, or any abbreviation of the name of the United Nations or UNHCR in connection with its business or otherwise.
4
5
  Sentence 1: 1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.
6
  Sentence 1: Either Party may terminate the working relationship contemplated by this Agreement by providing written notice to the other, provided, however, that the obligations and restrictions hereunder regarding the Confidential Information shall remain effective following any such termination or any other termination or expiration of this Agreement.
7
  Sentence 1: The Recipient shall not be precluded from disclosing the Confidential Information that is
  Sentence 2: (iv) at any time is developed by the Recipient completely independently of any disclosures hereunder.
8
9
  Sentence 1: 1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.

In [3]:
unique_values = pd.unique(df_short[['hypothesis', 'hypothesis_id']].values.ravel())
print(unique_values)

["Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information."
 'nda-11'
 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.'
 'nda-16'
 'Agreement shall not grant Receiving Party any right to Confidential Information.'
 'nda-15'
 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.'
 'nda-10'
 'Confidential Information shall only include technical information.'
 'nda-2'
 'All Confidential Information shall be expressly identified by the Disclosing Party.'
 'nda-1'
 'Some obligations of Agreement may survive termination of Agreement.'
 'nda-19'
 'Receiving Party may independently develop information similar to Confidential Information.'
 'nda-12'
 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.'
 'nda-20'
 'Confidential Information may include verbally conveyed information.'
 'nda-3'
 "Receiving Party shall not solicit some of Disclosing Party's representatives."
 'nda-18'
 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).'
 'nda-7'
 'Receiving Party may create a copy of some Confidential Information in some circumstances.'
 'nda-17'
 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.'
 'nda-8'
 'Receiving Party may acquire information similar to Confidential Information from a third party.'
 'nda-13'
 "Receiving Party may share some Confidential Information with some of Receiving Party's employees."
 'nda-5'
 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.'
 'nda-4']

In [24]:
for i in df_short[df_short['label'] == "contradiction"].iloc[0,]:
    print(i)

86
CopAcc_NDA-and-ToP-Mentors_2.0_2017.pdf
NON-DISCLOSURE AGREEMENT AND TERMS OF PARTICIPATION
Table of Content
1 Eligibility ..........................................................................................................................................2
2 Procedure and terms of participation ...............................................................................................3
3 Payment ..........................................................................................................................................4
4 Definition of confidential information ..............................................................................................4
5 Non-disclosure of confidential information / obligations of Mentor .................................................4
6 Discontinuation of use, return of materials ......................................................................................5
7 Notice of required disclosure ...........................................................................................................5
8 Proprietary rights, limited right to use ..............................................................................................6
9 Term ................................................................................................................................................6
10 Governing law ................................................................................................................................6
11 Jurisdiction .....................................................................................................................................6
12 Notification of unauthorised use ....................................................................................................6
13 Remedies .......................................................................................................................................7
14 Miscellaneous ................................................................................................................................7
Preamble
The Organiser of the Copernicus Masters and the Copernicus Accelerator 2017 is Anwendungszentrum GmbH Oberpfaffenhofen (hereinafter “Organiser”). The Earth monitoring competition Copernicus Masters aims to support the development of market-oriented applications based on Earth observation data. In 2017, the Copernicus Masters is again enriched by the Copernicus Accelerator, a European Commission programme. Through this initiative, the 50 best finalists of the Copernicus Masters, selected by an international expert panel will automatically be granted access to a business coaching scheme provided by high-level professionals, that will act as mentors. To actively participate in the Copernicus Accelerator programme, Mentor commits to the following Non-Disclosure-Agreement and Terms of Participation.
1 Eligibility
Mentor is a resident of one of the Copernicus participating countries1 or is employed with a legal identity registered in the territory of one of the Copernicus participating countries, willing to support and help develop the Ideas of the finalists of the Copernicus Masters 2017 (hereinafter “Participants”). Professionals who pursue becoming mentors need to apply via the dedicated platform, inserting all required details, which can be edited anytime by Mentor. Their request needs to be validated by the Organiser and the European Commission, who can refuse participation in case of non-eligibility or conflict of interest. After verification of all details entered, the Organiser will notify the Mentor about the outcome of his/her submission.
Even after validation, the Organiser cannot guarantee that there will be an actual match between Mentor and Participants. Mentor confirms that Mentor has not been involved in the development of any of the Ideas to be coached at any stage and that Mentor has no personal or commercial connection to any Participant of the Copernicus Accelerator that would influence an objective development of Ideas.
1 The Copernicus Participating countries include all the EU Member States, in addition to Norway and Iceland.
2 Procedure and Terms of Participation
The Copernicus Accelerator programme is comprised of different phases, for a total coaching support of approximately one year, aimed at helping Participants´ Ideas achieving measurable results. When submitting the request to become Mentor, Mentor needs to specify in which fields he/she can support Participants, in order to allow a suitable matchmaking with the requests and needs communicated by Participants.
When a Mentor is requested by a Participant of the programme, he/she can access the Participant's profile and examine the submitted idea, in order to decide whether to confirm the request or not. Mentors can only advise up to two participants.
Mentors will meet the Participants at the Accelerator Bootcamp, that will take place in line with the Awards Ceremony of the Copernicus Masters, the European Satellite Navigation Competition (ESNC), and the accompanying Satellite Masters Conference from 6 - 8 November 2017 in Tallinn, Estonia. Mentor´s participation to this event is mandatory, as it will set forth the official start of their relationship: Mentor and Participants will begin developing a coaching plan together, that will include objectives and KPIs of their affiliation.
Monthly virtual interactions need to be planned by Mentor, to ensure a continuous acceleration of the Participants Ideas´ towards business maturity. A mid-term review and survey will be required by April 2018, to evaluate progress made and ensure that the recommendations of the coaching plan are currently implemented by Participants. In case of a non-positive matching or non-compliance to his/her assigned duties (having monthly interactions with the mentees, keeping contacts with the Copernicus Accelerator team, promptly informing the organizers about any relevant issue connected to the coaching relationship), Mentor may be replaced by a more suitable candidate for the Participants´ needs.
Mentor will actively support Participants until July 2018, and will then submit a final report together, detailing the outcome of the coaching experience. The Organiser will continuously monitor all relationships, in order to assist both parties and guarantee a positive outcome of the programme. Mentor needs to deliver all requested reports and schedule all requested meetings. The Organiser will provide Mentor with templates for the documents to be produced. Mentors and Participants will meet again at the closing bootcamp, held in October/November 2018, that will official seal the closing of their mentoring relationship.
At the end of the coaching service, Mentor will fill in a questionnaire on the coaching service and the overall experience and will also be subject to a specific questionnaire compiled by Participants.
3 Payment
The Organiser will reimburse Mentor the travel arrangements and accommodation for the Acceleration Bootcamp in Tallinn in 2017 (a maximum of EUR 800) and the closing bootcamp in 2018 (a maximum of EUR 700). The coaching service provided by Mentor is worth a maximum fee of EUR 5,000 (VAT excluded) per Participant coached, that will be remunerated to Mentor at the end of the programme, after the submission and approval of the final summary report of the coaching relationships. Payment shall be made within 30 days from the receipt of invoice, and following the invoice verification by Organiser. No deductions will be made from the gross fees paid to mentor who shall be solely responsible for ensuring that all and any Government taxes and other deductions are paid by him/her.
4 Definition of Confidential Information
“Confidential Information” means any Idea disclosed to Mentor, all data and information, know-how, business concepts, software, procedures, products, services, development projects, and programmes contained in such Idea and/or its description and any conclusions. Confidential Information does not include:
> information already known or independently developed by Mentor prior to the disclosure of any Idea;
> information already in the public domain through no wrongful act of Mentor; or
> information received from a third party who was free to disclose such information.
In case of doubt any information is deemed to be Confidential Information unless Mentor proves that such information is not confidential.
5 Non-Disclosure of Confidential Information / Obligations of Mentor
Mentor shall not use any Confidential Information for any purpose except to review, assess and help develop the Participants´ Ideas.
Mentor shall not disclose any Confidential Information to any third party or to Mentor’s employees and/or employer without the prior written consent of the Participants. Mentor shall require his/her employees who will have access to Confidential Information to commit to a non-disclosure agreement that protects the Confidential Information to at least the same degree as this Agreement. Mentor shall take all reasonable measures to protect the secrecy of, and avoid any unauthorised disclosure or use of Confidential Information. Such measures shall include the highest degree of care that Mentor utilises to protect Mentor’s own confidential information of a similar nature, but no less than reasonable care.
Notwithstanding Mentor’s right to assess and rate the Ideas of the Participants, Mentor shall not use the Confidential information for his/her own or third parties purposes and shall not file for any intellectual property right protection for the Confidential Information or parts of it.
Mentor shall notify Organiser immediately in writing of any misuse or misappropriation of any Confidential Information that may come to Mentor’s attention. Mentor agrees to segregate all Confidential Information relating to this agreement from Confidential Information of others to avoid commingling.
6 Discontinuation of Use, Return of Materials
At Organiser’s first request, Mentor shall:
(a) discontinue all use of Confidential Information;
(b) return to Organiser and/or Participants all materials furnished by Organiser and/or Participants that contain Confidential Information;
(c) destroy any copy and all materials produced by and under control of Organiser and/or Participants that contain Confidential Information;
(d) erase and/or destroy any Confidential Information contained in computer memory or data storage apparatus of, under control of or used by Mentor;
(e) remove the Confidential Information from any software or data base of, under control of/or used by Mentor that incorporates or uses the Confidential Information in whole or in part; and
(f) warrant in writing to Organiser, within ten (10) days after Organiser’s request, that Mentor has taken all actions set out under (a) through (e) in this Clause 4.
7 Notice of Required Disclosure
If Mentor is required by mandatory, non-appealable judicial or administrative process and/or order to disclose Confidential Information, then Mentor shall promptly notify Organiser and allow Organiser and the Participants reasonable time to oppose such process unless this is not admissible under a mandatory law, judicial or administrative order. Notwithstanding the foregoing, Mentor shall disclose Confidential Information only to the minimum extent required to comply with such order.
8 Proprietary Rights, Limited Right to Use
Any and all proprietary rights, including but not limited to rights to and in inventions, patent rights, utility models, copyrights, trademarks and trade secrets, in and to any Confidential Information shall be and remain with the Participants respectively, and Mentor shall not have any right, license, title or interest in or to any Confidential Information, except the limited right to review, assess and help develop such Confidential Information in connection with the Copernicus Accelerator 2017.
9 Term
This Agreement shall be effective as of 2 May 2017 and may not be terminated except for important cause. Notwithstanding the termination of this Agreement, any Confidential Information must be kept confidential for as long as such Confidential Information is not publicly known unless it becomes part of the public domain through no wrongful act of Mentor. This agreement may not be changed or modified, except by an agreement in writing, signed by both parties.
10 Governing Law
This Agreement and the rights and obligations of the parties hereunder shall be governed by the material laws of the Federal Republic of Germany.
11 Jurisdiction
The place of jurisdiction for any and all legal disputes arising out of or in connection with this Agreement is Munich (Landgericht München I). Imperative places of jurisdiction under German Law shall remain unaffected by the foregoing.
12 Notification of Unauthorised Use
Mentor shall notify Organiser immediately upon discovery of any unauthorised use or disclosure of Confidential Information or any other breach of this Agreement by Mentor, and will cooperate with
Organiser in every reasonable way to help Organiser regain possession of the Confidential Information and prevent its further unauthorised use or publication.
13 Remedies
Mentor acknowledges that his/her obligations under this Agreement are necessary and reasonable in order to protect the Ideas and the Confidential Information. Each party further acknowledges that any breach by Mentor of Mentor’s covenants and agreements set forth in this Agreement or threatened violation of such may cause irreparable injury to Organiser and to Participants.
14 Miscellaneous
This Agreement shall be binding upon Organiser and Mentor, and their successors and assigns. This Agreement contains the entire agreement and understanding of the parties relating to the subject matter hereof and supersedes all prior discussions, agreements and understandings of every nature between them. This Agreement may not be changed or modified, except by an agreement in writing, signed by both
of the parties.
The failure or delay on the part of either party to exercise any right under this Agreement shall not be deemed a waiver of any rights under this Agreement.
Mentor is aware that an unauthorised disclosure of the Ideas and of the assessment and development of the Ideas and of any Confidential Information may lead to serious damage to Participants and the Organiser of the Copernicus Accelerator 2017. This Agreement shall be for the benefit of the Participants.
The Organiser and the European Commission will use the Mentor´s contact information to inform him/her of all matters related to the Copernicus Accelerator 2017 and of any other issues the Organiser and the European Commission deem relevant and appropriate. The failure or delay on the part of either party to exercise any right under this agreement shall not be deemed a waiver of any rights under this agreement.

nda-2
Confidential Information shall only include technical information.
contradiction
[array([7752, 8016], dtype=int64)]
['“Confidential Information” means any Idea disclosed to Mentor, all data and information, know-how, business concepts, software, procedures, products, services, development projects, and programmes contained in such Idea and/or its description and any conclusions. ']

In [28]:
print(df_short[df_short['document_id'] == 86]['text'].iloc[0])

NON-DISCLOSURE AGREEMENT AND TERMS OF PARTICIPATION
Table of Content
1 Eligibility ..........................................................................................................................................2
2 Procedure and terms of participation ...............................................................................................3
3 Payment ..........................................................................................................................................4
4 Definition of confidential information ..............................................................................................4
5 Non-disclosure of confidential information / obligations of Mentor .................................................4
6 Discontinuation of use, return of materials ......................................................................................5
7 Notice of required disclosure ...........................................................................................................5
8 Proprietary rights, limited right to use ..............................................................................................6
9 Term ................................................................................................................................................6
10 Governing law ................................................................................................................................6
11 Jurisdiction .....................................................................................................................................6
12 Notification of unauthorised use ....................................................................................................6
13 Remedies .......................................................................................................................................7
14 Miscellaneous ................................................................................................................................7
Preamble
The Organiser of the Copernicus Masters and the Copernicus Accelerator 2017 is Anwendungszentrum GmbH Oberpfaffenhofen (hereinafter “Organiser”). The Earth monitoring competition Copernicus Masters aims to support the development of market-oriented applications based on Earth observation data. In 2017, the Copernicus Masters is again enriched by the Copernicus Accelerator, a European Commission programme. Through this initiative, the 50 best finalists of the Copernicus Masters, selected by an international expert panel will automatically be granted access to a business coaching scheme provided by high-level professionals, that will act as mentors. To actively participate in the Copernicus Accelerator programme, Mentor commits to the following Non-Disclosure-Agreement and Terms of Participation.
1 Eligibility
Mentor is a resident of one of the Copernicus participating countries1 or is employed with a legal identity registered in the territory of one of the Copernicus participating countries, willing to support and help develop the Ideas of the finalists of the Copernicus Masters 2017 (hereinafter “Participants”). Professionals who pursue becoming mentors need to apply via the dedicated platform, inserting all required details, which can be edited anytime by Mentor. Their request needs to be validated by the Organiser and the European Commission, who can refuse participation in case of non-eligibility or conflict of interest. After verification of all details entered, the Organiser will notify the Mentor about the outcome of his/her submission.
Even after validation, the Organiser cannot guarantee that there will be an actual match between Mentor and Participants. Mentor confirms that Mentor has not been involved in the development of any of the Ideas to be coached at any stage and that Mentor has no personal or commercial connection to any Participant of the Copernicus Accelerator that would influence an objective development of Ideas.
1 The Copernicus Participating countries include all the EU Member States, in addition to Norway and Iceland.
2 Procedure and Terms of Participation
The Copernicus Accelerator programme is comprised of different phases, for a total coaching support of approximately one year, aimed at helping Participants´ Ideas achieving measurable results. When submitting the request to become Mentor, Mentor needs to specify in which fields he/she can support Participants, in order to allow a suitable matchmaking with the requests and needs communicated by Participants.
When a Mentor is requested by a Participant of the programme, he/she can access the Participant's profile and examine the submitted idea, in order to decide whether to confirm the request or not. Mentors can only advise up to two participants.
Mentors will meet the Participants at the Accelerator Bootcamp, that will take place in line with the Awards Ceremony of the Copernicus Masters, the European Satellite Navigation Competition (ESNC), and the accompanying Satellite Masters Conference from 6 - 8 November 2017 in Tallinn, Estonia. Mentor´s participation to this event is mandatory, as it will set forth the official start of their relationship: Mentor and Participants will begin developing a coaching plan together, that will include objectives and KPIs of their affiliation.
Monthly virtual interactions need to be planned by Mentor, to ensure a continuous acceleration of the Participants Ideas´ towards business maturity. A mid-term review and survey will be required by April 2018, to evaluate progress made and ensure that the recommendations of the coaching plan are currently implemented by Participants. In case of a non-positive matching or non-compliance to his/her assigned duties (having monthly interactions with the mentees, keeping contacts with the Copernicus Accelerator team, promptly informing the organizers about any relevant issue connected to the coaching relationship), Mentor may be replaced by a more suitable candidate for the Participants´ needs.
Mentor will actively support Participants until July 2018, and will then submit a final report together, detailing the outcome of the coaching experience. The Organiser will continuously monitor all relationships, in order to assist both parties and guarantee a positive outcome of the programme. Mentor needs to deliver all requested reports and schedule all requested meetings. The Organiser will provide Mentor with templates for the documents to be produced. Mentors and Participants will meet again at the closing bootcamp, held in October/November 2018, that will official seal the closing of their mentoring relationship.
At the end of the coaching service, Mentor will fill in a questionnaire on the coaching service and the overall experience and will also be subject to a specific questionnaire compiled by Participants.
3 Payment
The Organiser will reimburse Mentor the travel arrangements and accommodation for the Acceleration Bootcamp in Tallinn in 2017 (a maximum of EUR 800) and the closing bootcamp in 2018 (a maximum of EUR 700). The coaching service provided by Mentor is worth a maximum fee of EUR 5,000 (VAT excluded) per Participant coached, that will be remunerated to Mentor at the end of the programme, after the submission and approval of the final summary report of the coaching relationships. Payment shall be made within 30 days from the receipt of invoice, and following the invoice verification by Organiser. No deductions will be made from the gross fees paid to mentor who shall be solely responsible for ensuring that all and any Government taxes and other deductions are paid by him/her.
4 Definition of Confidential Information
“Confidential Information” means any Idea disclosed to Mentor, all data and information, know-how, business concepts, software, procedures, products, services, development projects, and programmes contained in such Idea and/or its description and any conclusions. Confidential Information does not include:
> information already known or independently developed by Mentor prior to the disclosure of any Idea;
> information already in the public domain through no wrongful act of Mentor; or
> information received from a third party who was free to disclose such information.
In case of doubt any information is deemed to be Confidential Information unless Mentor proves that such information is not confidential.
5 Non-Disclosure of Confidential Information / Obligations of Mentor
Mentor shall not use any Confidential Information for any purpose except to review, assess and help develop the Participants´ Ideas.
Mentor shall not disclose any Confidential Information to any third party or to Mentor’s employees and/or employer without the prior written consent of the Participants. Mentor shall require his/her employees who will have access to Confidential Information to commit to a non-disclosure agreement that protects the Confidential Information to at least the same degree as this Agreement. Mentor shall take all reasonable measures to protect the secrecy of, and avoid any unauthorised disclosure or use of Confidential Information. Such measures shall include the highest degree of care that Mentor utilises to protect Mentor’s own confidential information of a similar nature, but no less than reasonable care.
Notwithstanding Mentor’s right to assess and rate the Ideas of the Participants, Mentor shall not use the Confidential information for his/her own or third parties purposes and shall not file for any intellectual property right protection for the Confidential Information or parts of it.
Mentor shall notify Organiser immediately in writing of any misuse or misappropriation of any Confidential Information that may come to Mentor’s attention. Mentor agrees to segregate all Confidential Information relating to this agreement from Confidential Information of others to avoid commingling.
6 Discontinuation of Use, Return of Materials
At Organiser’s first request, Mentor shall:
(a) discontinue all use of Confidential Information;
(b) return to Organiser and/or Participants all materials furnished by Organiser and/or Participants that contain Confidential Information;
(c) destroy any copy and all materials produced by and under control of Organiser and/or Participants that contain Confidential Information;
(d) erase and/or destroy any Confidential Information contained in computer memory or data storage apparatus of, under control of or used by Mentor;
(e) remove the Confidential Information from any software or data base of, under control of/or used by Mentor that incorporates or uses the Confidential Information in whole or in part; and
(f) warrant in writing to Organiser, within ten (10) days after Organiser’s request, that Mentor has taken all actions set out under (a) through (e) in this Clause 4.
7 Notice of Required Disclosure
If Mentor is required by mandatory, non-appealable judicial or administrative process and/or order to disclose Confidential Information, then Mentor shall promptly notify Organiser and allow Organiser and the Participants reasonable time to oppose such process unless this is not admissible under a mandatory law, judicial or administrative order. Notwithstanding the foregoing, Mentor shall disclose Confidential Information only to the minimum extent required to comply with such order.
8 Proprietary Rights, Limited Right to Use
Any and all proprietary rights, including but not limited to rights to and in inventions, patent rights, utility models, copyrights, trademarks and trade secrets, in and to any Confidential Information shall be and remain with the Participants respectively, and Mentor shall not have any right, license, title or interest in or to any Confidential Information, except the limited right to review, assess and help develop such Confidential Information in connection with the Copernicus Accelerator 2017.
9 Term
This Agreement shall be effective as of 2 May 2017 and may not be terminated except for important cause. Notwithstanding the termination of this Agreement, any Confidential Information must be kept confidential for as long as such Confidential Information is not publicly known unless it becomes part of the public domain through no wrongful act of Mentor. This agreement may not be changed or modified, except by an agreement in writing, signed by both parties.
10 Governing Law
This Agreement and the rights and obligations of the parties hereunder shall be governed by the material laws of the Federal Republic of Germany.
11 Jurisdiction
The place of jurisdiction for any and all legal disputes arising out of or in connection with this Agreement is Munich (Landgericht München I). Imperative places of jurisdiction under German Law shall remain unaffected by the foregoing.
12 Notification of Unauthorised Use
Mentor shall notify Organiser immediately upon discovery of any unauthorised use or disclosure of Confidential Information or any other breach of this Agreement by Mentor, and will cooperate with
Organiser in every reasonable way to help Organiser regain possession of the Confidential Information and prevent its further unauthorised use or publication.
13 Remedies
Mentor acknowledges that his/her obligations under this Agreement are necessary and reasonable in order to protect the Ideas and the Confidential Information. Each party further acknowledges that any breach by Mentor of Mentor’s covenants and agreements set forth in this Agreement or threatened violation of such may cause irreparable injury to Organiser and to Participants.
14 Miscellaneous
This Agreement shall be binding upon Organiser and Mentor, and their successors and assigns. This Agreement contains the entire agreement and understanding of the parties relating to the subject matter hereof and supersedes all prior discussions, agreements and understandings of every nature between them. This Agreement may not be changed or modified, except by an agreement in writing, signed by both
of the parties.
The failure or delay on the part of either party to exercise any right under this Agreement shall not be deemed a waiver of any rights under this Agreement.
Mentor is aware that an unauthorised disclosure of the Ideas and of the assessment and development of the Ideas and of any Confidential Information may lead to serious damage to Participants and the Organiser of the Copernicus Accelerator 2017. This Agreement shall be for the benefit of the Participants.
The Organiser and the European Commission will use the Mentor´s contact information to inform him/her of all matters related to the Copernicus Accelerator 2017 and of any other issues the Organiser and the European Commission deem relevant and appropriate. The failure or delay on the part of either party to exercise any right under this agreement shall not be deemed a waiver of any rights under this agreement.

In [39]:
df_short[df_short['document_id'] == 86][['hypothesis_id', 'hypothesis', 'label', 'evidence_texts']]

,hypothesis_id,hypothesis,label,evidence_texts
17,nda-11,Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confident...,notmentioned,[]
18,nda-16,Receiving Party shall destroy or return some Confidential Information upon the termination of Ag...,notmentioned,[]
19,nda-15,Agreement shall not grant Receiving Party any right to Confidential Information.,entailment,"[Any and all proprietary rights, including but not limited to rights to and in inventions, paten..."
20,nda-10,Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.,notmentioned,[]
21,nda-2,Confidential Information shall only include technical information.,contradiction,"[“Confidential Information” means any Idea disclosed to Mentor, all data and information, know-h..."
22,nda-1,All Confidential Information shall be expressly identified by the Disclosing Party.,notmentioned,[]
23,nda-19,Some obligations of Agreement may survive termination of Agreement.,entailment,"[Notwithstanding the termination of this Agreement, any Confidential Information must be kept co..."
24,nda-12,Receiving Party may independently develop information similar to Confidential Information.,notmentioned,[]
25,nda-20,Receiving Party may retain some Confidential Information even after the return or destruction of...,contradiction,"[At Organiser’s first request, Mentor shall:, (d) erase and/or destroy any Confidential Informat..."
26,nda-3,Confidential Information may include verbally conveyed information.,notmentioned,[]
27,nda-18,Receiving Party shall not solicit some of Disclosing Party's representatives.,notmentioned,[]
28,nda-7,Receiving Party may share some Confidential Information with some third-parties (including consu...,contradiction,[Mentor shall not disclose any Confidential Information to any third party or to Mentor’s employ...
29,nda-17,Receiving Party may create a copy of some Confidential Information in some circumstances.,notmentioned,[]
30,nda-8,"Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regula...",entailment,"[If Mentor is required by mandatory, non-appealable judicial or administrative process and/or or..."
31,nda-13,Receiving Party may acquire information similar to Confidential Information from a third party.,entailment,"[Confidential Information does not include:, > information received from a third party who was f..."
32,nda-5,Receiving Party may share some Confidential Information with some of Receiving Party's employees.,contradiction,[Mentor shall not disclose any Confidential Information to any third party or to Mentor’s employ...
33,nda-4,Receiving Party shall not use any Confidential Information for any purpose other than the purpos...,entailment,"[Mentor shall not use any Confidential Information for any purpose except to review, assess and ..."

In [60]:
x = df_short[df_short['document_id'] == 86][['hypothesis_id', 'hypothesis', 'label', 'evidence_texts']]
x.rename(columns={"evidence_texts":"source_clause"}, inplace=True)

def join_text(row):
    joined = ". ".join(row['source_clause'])
    return joined

x['source_clause'] = x.apply(join_text, axis=1)
x.to_dict(orient="records")

[{'hypothesis_id': 'nda-11',
  'hypothesis': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information.",
  'label': 'notmentioned',
  'source_clause': ''},
 {'hypothesis_id': 'nda-16',
  'hypothesis': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.',
  'label': 'notmentioned',
  'source_clause': ''},
 {'hypothesis_id': 'nda-15',
  'hypothesis': 'Agreement shall not grant Receiving Party any right to Confidential Information.',
  'label': 'entailment',
  'source_clause': 'Any and all proprietary rights, including but not limited to rights to and in inventions, patent rights, utility models, copyrights, trademarks and trade secrets, in and to any Confidential Information shall be and remain with the Participants respectively, and Mentor shall not have any right, license, title or interest in or to any Confidential Information, except the limited right to review, assess and help develop such Confidential Information in connection with the Copernicus Accelerator 2017.'},
 {'hypothesis_id': 'nda-10',
  'hypothesis': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.',
  'label': 'notmentioned',
  'source_clause': ''},
 {'hypothesis_id': 'nda-2',
  'hypothesis': 'Confidential Information shall only include technical information.',
  'label': 'contradiction',
  'source_clause': '“Confidential Information” means any Idea disclosed to Mentor, all data and information, know-how, business concepts, software, procedures, products, services, development projects, and programmes contained in such Idea and/or its description and any conclusions. '},
 {'hypothesis_id': 'nda-1',
  'hypothesis': 'All Confidential Information shall be expressly identified by the Disclosing Party.',
  'label': 'notmentioned',
  'source_clause': ''},
 {'hypothesis_id': 'nda-19',
  'hypothesis': 'Some obligations of Agreement may survive termination of Agreement.',
  'label': 'entailment',
  'source_clause': 'Notwithstanding the termination of this Agreement, any Confidential Information must be kept confidential for as long as such Confidential Information is not publicly known unless it becomes part of the public domain through no wrongful act of Mentor. '},
 {'hypothesis_id': 'nda-12',
  'hypothesis': 'Receiving Party may independently develop information similar to Confidential Information.',
  'label': 'notmentioned',
  'source_clause': ''},
 {'hypothesis_id': 'nda-20',
  'hypothesis': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.',
  'label': 'contradiction',
  'source_clause': 'At Organiser’s first request, Mentor shall:. (d) erase and/or destroy any Confidential Information contained in computer memory or data storage apparatus of, under control of or used by Mentor;. (e) remove the Confidential Information from any software or data base of, under control of/or used by Mentor that incorporates or uses the Confidential Information in whole or in part; and'},
 {'hypothesis_id': 'nda-3',
  'hypothesis': 'Confidential Information may include verbally conveyed information.',
  'label': 'notmentioned',
  'source_clause': ''},
 {'hypothesis_id': 'nda-18',
  'hypothesis': "Receiving Party shall not solicit some of Disclosing Party's representatives.",
  'label': 'notmentioned',
  'source_clause': ''},
 {'hypothesis_id': 'nda-7',
  'hypothesis': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).',
  'label': 'contradiction',
  'source_clause': 'Mentor shall not disclose any Confidential Information to any third party or to Mentor’s employees and/or employer without the prior written consent of the Participants. '},
 {'hypothesis_id': 'nda-17',
  'hypothesis': 'Receiving Party may create a copy of some Confidential Information in some circumstances.',
  'label': 'notmentioned',
  'source_clause': ''},
 {'hypothesis_id': 'nda-8',
  'hypothesis': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.',
  'label': 'entailment',
  'source_clause': 'If Mentor is required by mandatory, non-appealable judicial or administrative process and/or order to disclose Confidential Information, then Mentor shall promptly notify Organiser and allow Organiser and the Participants reasonable time to oppose such process unless this is not admissible under a mandatory law, judicial or administrative order. '},
 {'hypothesis_id': 'nda-13',
  'hypothesis': 'Receiving Party may acquire information similar to Confidential Information from a third party.',
  'label': 'entailment',
  'source_clause': 'Confidential Information does not include:. > information received from a third party who was free to disclose such information.'},
 {'hypothesis_id': 'nda-5',
  'hypothesis': "Receiving Party may share some Confidential Information with some of Receiving Party's employees.",
  'label': 'contradiction',
  'source_clause': 'Mentor shall not disclose any Confidential Information to any third party or to Mentor’s employees and/or employer without the prior written consent of the Participants. '},
 {'hypothesis_id': 'nda-4',
  'hypothesis': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.',
  'label': 'entailment',
  'source_clause': 'Mentor shall not use any Confidential Information for any purpose except to review, assess and help develop the Participants´ Ideas.'}]