In [1]:
import mlrun

from dotenv import load_dotenv
# Loads AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and MLRUN_AWS_ROLE_ARN
load_dotenv() 

import os
# https://docs.mlrun.org/en/stable/store/datastore.html#s3
# print(os.environ['AWS_ACCESS_KEY_ID'])
# print(os.environ['AWS_SECRET_ACCESS_KEY'])
# print(os.environ['MLRUN_AWS_ROLE_ARN'])

c:\Work\Folder_1\Project_folder\LLM_project_3_FineTune_MLOps\Finetune-legal-llm-mlops\.venv\lib\site-packages\google\auth\__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
c:\Work\Folder_1\Project_folder\LLM_project_3_FineTune_MLOps\Finetune-legal-llm-mlops\.venv\lib\site-packages\google\oauth2\__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

In [2]:
from pathlib import Path

artifact_path = Path.cwd().parent / "mlrun-data/"
artifact_path = str(artifact_path.as_posix()) # convert windows path to unix path
artifact_path = "file://" + artifact_path
print(artifact_path)
p = mlrun.set_environment("http://localhost:8080", artifact_path=artifact_path)

file://c:/Work/Folder_1/Project_folder/LLM_project_3_FineTune_MLOps/Finetune-legal-llm-mlops/mlrun-data

In [3]:
project = mlrun.load_project(name='finetune-legal-extractor', context="../") # project yaml must be in this directory

# Verify it loaded correctly by checking its status or printing the config
# print(project.to_yaml())

In [4]:
pipeline_run = project.run(
    name="register_datasets",
    arguments={
        "source_path": "s3://legal-llama-data",
        "version": "1.0.0"
    },
    local=True,   # Run the pipeline sequence locally
    watch=True    # Print the progress to the console
)

> 2026-03-30 19:43:44,374 [warning] WARNING!, You seem to have uncommitted git changes, use .push()

> 2026-03-30 19:43:44,498 [info] Storing function: {'name': 'data-register-function-register-processed-data', 'uid': '5ba9360bd6cf4809825a25512a95637a', 'db': None}

> 2026-03-30 19:44:05,975 [info] Run execution finished: {'status': 'completed', 'name': 'data-register-function-register-processed-data'}
> 2026-03-30 19:44:05,977 [info] Storing function: {'name': 'data-register-function-register-processed-data', 'uid': '9aefb0686d8443cea2aaa2c92e73ecde', 'db': None}

> 2026-03-30 19:44:11,068 [info] Run execution finished: {'status': 'completed', 'name': 'data-register-function-register-processed-data'}
> 2026-03-30 19:44:11,068 [info] Storing function: {'name': 'data-register-function-register-processed-data', 'uid': '890ba851a46743d69810fa23b3c5b349', 'db': None}

> 2026-03-30 19:44:15,075 [info] Run execution finished: {'status': 'completed', 'name': 'data-register-function-register-processed-data'}

> 2026-03-30 19:44:15,087 [info] Started run workflow finetune-legal-extractor-register_datasets with run id = '672ca153389641bdb1ffc45a58f02cff' by local engine

In [5]:
project.save()

In [6]:
project.spec.get_code_path()

'../'