In [1]:
import mlrun

from dotenv import load_dotenv
# Loads AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and MLRUN_AWS_ROLE_ARN
load_dotenv() 

import os
# https://docs.mlrun.org/en/stable/store/datastore.html#s3
# print(os.environ['AWS_ACCESS_KEY_ID'])
# print(os.environ['AWS_SECRET_ACCESS_KEY'])
# print(os.environ['MLRUN_AWS_ROLE_ARN'])

from pathlib import Path

artifact_path = Path.cwd().parent / "mlrun-data/"
artifact_path = str(artifact_path.as_posix()) # convert windows path to unix path
artifact_path = "file://" + artifact_path
print(artifact_path)
p = mlrun.set_environment(api_path="http://localhost:8080", artifact_path=artifact_path)

c:\Work\Folder_1\Project_folder\LLM_project_3_FineTune_MLOps\Finetune-legal-llm-mlops\.venv\lib\site-packages\google\auth\__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
c:\Work\Folder_1\Project_folder\LLM_project_3_FineTune_MLOps\Finetune-legal-llm-mlops\.venv\lib\site-packages\google\oauth2\__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

file://c:/Work/Folder_1/Project_folder/LLM_project_3_FineTune_MLOps/Finetune-legal-llm-mlops/mlrun-data

In [2]:
project = mlrun.load_project(name='finetune-legal-extractor', context="../") # project yaml must be in this directory

# Verify it loaded correctly by checking its status or printing the config
# print(project.to_yaml())

In [4]:
os.environ["MLRUN_DBPATH"] = "http://localhost:8080"

In [7]:
from datetime import datetime

run_obj = project.run(
    name="register_raw_datasets",
    arguments={
        "source_path": "s3://legal-llama-data/raw",
        "version": datetime.now().strftime("%Y%m%d_%H%M")
    },
    local=True,   # Run the pipeline sequence locally
    watch=True    # Print the progress to the console
)

> 2026-04-05 18:35:52,493 [warning] WARNING!, You seem to have uncommitted git changes, use .push()

> 2026-04-05 18:35:52,500 [info] Storing function: {"db":null,"name":"raw-proc-process-raw","uid":"4d5799731d6d4cfcaf5fe5852db725f8"}
s3://legal-llama-data/raw/train.parquet processed and written to s3://legal-llama-data/processed_training/20260405_1835

> 2026-04-05 18:36:10,300 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}
> 2026-04-05 18:36:10,307 [info] Storing function: {"db":null,"name":"raw-proc-process-raw","uid":"d7b5c735d40d44e096a1d1bc373733f9"}
s3://legal-llama-data/raw/validation.parquet processed and written to s3://legal-llama-data/processed_training/20260405_1835

> 2026-04-05 18:36:20,454 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}
> 2026-04-05 18:36:20,456 [info] Storing function: {"db":null,"name":"raw-proc-process-raw","uid":"15521f4054404450a3bb66e41708c7d3"}
s3://legal-llama-data/raw/test.parquet processed and written to s3://legal-llama-data/processed_training/20260405_1835

> 2026-04-05 18:36:37,397 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}

> 2026-04-05 18:36:37,532 [info] Started run workflow finetune-legal-extractor-register_raw_datasets with run id = '65b75eb10d0a4c57aaba0038b9593aff' by local engine

In [ ]:
## Testing direct access to S3 data
data_uri = "s3://legal-llama-data/raw/test.parquet"

# Fetch the item and immediately convert it to a Pandas DataFrame
df = mlrun.get_dataitem(data_uri).as_df()
df.head()

In [9]:
## Testing data versioning and access to registered datasets in MLRun
data_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_test_data:latest"
data_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_test_data:20260405_1822"

# Fetch the item and immediately convert it to a Pandas DataFrame
df = mlrun.get_dataitem(data_uri).as_df()
df.head()

,id,document_id,text,inference,timestamp,origin
0,b2041ab2-0be9-426c-96a9-f923b54bbb29,1,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,[{'hypothesis': 'Receiving Party shall destroy...,2026-04-05 18:23:06.438962,downloaded
1,86cd95a9-4804-4891-9ce4-49c77c91ff13,2,MUTUAL NON-DISCLOSURE AGREEMENT\nBetween\nAND\...,"[{'hypothesis': ""Receiving Party shall not rev...",2026-04-05 18:23:06.438962,downloaded
2,94be4ef8-e72d-403b-97b2-2442920c8945,4,Non-Disclosure Agreement\nDate:\nParties: [NAM...,[{'hypothesis': 'Agreement shall not grant Rec...,2026-04-05 18:23:06.438962,downloaded
3,ed91764a-1b58-4ef0-8b58-6c15e02e3597,5,Confidentiality Agreement\nThis Confidentialit...,[{'hypothesis': 'Receiving Party shall not dis...,2026-04-05 18:23:06.438962,downloaded
4,136de4a1-e2b2-423f-844c-bc3822ad0476,6,MUTUAL NON-DISCLOSURE/CONFIDENTIALITY AGREEMEN...,[{'hypothesis': 'Receiving Party shall destroy...,2026-04-05 18:23:06.438962,downloaded

In [3]:
# This deletes all artifacts in the database
db = mlrun.get_run_db()
# Wipe all artifacts (including datasets) from this specific project
db.del_artifacts(project=project.metadata.name)

In [10]:
project.spec.get_code_path()

'../'