In [1]:
import mlrun

from dotenv import load_dotenv
# Loads AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and MLRUN_AWS_ROLE_ARN
load_dotenv() 

import os
# https://docs.mlrun.org/en/stable/store/datastore.html#s3
# print(os.environ['AWS_ACCESS_KEY_ID'])
# print(os.environ['AWS_SECRET_ACCESS_KEY'])
# print(os.environ['MLRUN_AWS_ROLE_ARN'])

from pathlib import Path

artifact_path = Path.cwd().parent #/ "mlrun-data/"
artifact_path = str(artifact_path.as_posix()) # convert windows path to unix path
artifact_path = "file://" + artifact_path
print(artifact_path)
p = mlrun.set_environment(api_path="http://localhost:8080", artifact_path=artifact_path)

c:\Work\Folder_1\Project_folder\LLM_project_3_FineTune_MLOps\Finetune-legal-llm-mlops\.venv\lib\site-packages\google\auth\__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
c:\Work\Folder_1\Project_folder\LLM_project_3_FineTune_MLOps\Finetune-legal-llm-mlops\.venv\lib\site-packages\google\oauth2\__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

file://c:/Work/Folder_1/Project_folder/LLM_project_3_FineTune_MLOps/Finetune-legal-llm-mlops

In [2]:
project = mlrun.load_project(name='finetune-legal-extractor', context="../") # project yaml must be in this directory

# Verify it loaded correctly by checking its status or printing the config
# print(project.to_yaml())

In [3]:
from datetime import datetime

run_obj = project.run(
    name="register_raw_datasets",
    arguments={
        "source_path": "s3://legal-llama-data/raw",
        "version": datetime.now().strftime("%Y%m%d_%H%M")
    },
    local=True,   # Run the pipeline sequence locally
    watch=True    # Print the progress to the console
)

> 2026-04-06 21:10:13,185 [warning] WARNING!, You seem to have uncommitted git changes, use .push()

> 2026-04-06 21:10:13,328 [info] Storing function: {"db":null,"name":"raw-proc-process-raw","uid":"c357297eced44da6b840186f6a04dd92"}
s3://legal-llama-data/raw/train.parquet processed and written to s3://legal-llama-data/processed_training/20260406_2110

> 2026-04-06 21:10:32,497 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}
> 2026-04-06 21:10:32,501 [info] Storing function: {"db":null,"name":"raw-proc-process-raw","uid":"e20f8e72f5fd40499284208956327869"}
s3://legal-llama-data/raw/validation.parquet processed and written to s3://legal-llama-data/processed_training/20260406_2110

> 2026-04-06 21:10:37,636 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}
> 2026-04-06 21:10:37,640 [info] Storing function: {"db":null,"name":"raw-proc-process-raw","uid":"91dbcf3cc98b40dca9ea245fc3efde55"}
s3://legal-llama-data/raw/test.parquet processed and written to s3://legal-llama-data/processed_training/20260406_2110

> 2026-04-06 21:10:44,533 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}

> 2026-04-06 21:10:44,728 [info] Started run workflow finetune-legal-extractor-register_raw_datasets with run id = '9fb6f491eb4b4159863282d1e73ffc69' by local engine

In [5]:
## Testing direct access to S3 data
data_uri = "s3://legal-llama-data/raw/test.parquet"

# Fetch the item and immediately convert it to a Pandas DataFrame
df = mlrun.get_dataitem(data_uri).as_df()
df.head()

,document_id,file_name,text,hypothesis_id,hypothesis,label,evidence_spans,evidence_texts
0,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-11,Receiving Party shall not reverse engineer any...,notmentioned,[],[]
1,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-16,Receiving Party shall destroy or return some C...,entailment,"[[12366, 12998], [12999, 13094], [13095, 13136]]",[The Recipient shall immediately return and re...
2,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-15,Agreement shall not grant Receiving Party any ...,entailment,"[[6094, 6220]]","[No other right or license, whether expressed ..."
3,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-10,Receiving Party shall not disclose the fact th...,notmentioned,[],[]
4,1,064-19 Non Disclosure Agreement 2019.pdf,NON-DISCLOSURE AGREEMENT\nRequired under JEA's...,nda-2,Confidential Information shall only include te...,contradiction,"[[3254, 3518], [4167, 4394]]","[For purposes of this Agreement, ""Confidential..."

In [7]:
df.head().iloc[0]['inference']

array(['{\'hypothesis_id\': \'nda-11\', \'hypothesis\': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party\'s Confidential Information.", \'source_clause\': \'\', \'hypothesis_label\': \'not_mentioned\'}',
       "{'hypothesis_id': 'nda-16', 'hypothesis': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.', 'source_clause': '5. All Confidential Information in any form and any medium, including all copies thereof, disclosed to the Recipient shall be returned to UNHCR or destroyed: \\n(a) if a business relationship is not entered into with UNHCR on or before the date which is three (3) months after the date both Parties have signed the Agreement; or ', 'hypothesis_label': 'entailment'}",
       "{'hypothesis_id': 'nda-15', 'hypothesis': 'Agreement shall not grant Receiving Party any right to Confidential Information.', 'source_clause': '4. Nothing in this Agreement is to be construed as granting the Recipient, by implication or otherwise, any right whatsoever with respect to the Confidential Information or part thereof.', 'hypothesis_label': 'entailment'}",
       "{'hypothesis_id': 'nda-10', 'hypothesis': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.', 'source_clause': '11. The Recipient shall not advertise or otherwise make public the fact that it has a confidential relationship with UNHCR, nor shall the Recipient, in any manner whatsoever use the name, emblem, or official seal of the United Nations or UNHCR, or any abbreviation of the name of the United Nations or UNHCR in connection with its business or otherwise.', 'hypothesis_label': 'entailment'}",
       "{'hypothesis_id': 'nda-2', 'hypothesis': 'Confidential Information shall only include technical information.', 'source_clause': '', 'hypothesis_label': 'not_mentioned'}",
       "{'hypothesis_id': 'nda-1', 'hypothesis': 'All Confidential Information shall be expressly identified by the Disclosing Party.', 'source_clause': '1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.', 'hypothesis_label': 'entailment'}",
       "{'hypothesis_id': 'nda-19', 'hypothesis': 'Some obligations of Agreement may survive termination of Agreement.', 'source_clause': 'Either Party may terminate the working relationship contemplated by this Agreement by providing written notice to the other, provided, however, that the obligations and restrictions hereunder regarding the Confidential Information shall remain effective following any such termination or any other termination or expiration of this Agreement.', 'hypothesis_label': 'entailment'}",
       "{'hypothesis_id': 'nda-12', 'hypothesis': 'Receiving Party may independently develop information similar to Confidential Information.', 'source_clause': 'The Recipient shall not be precluded from disclosing the Confidential Information that is \\n(iv) at any time is developed by the Recipient completely independently of any disclosures hereunder.', 'hypothesis_label': 'entailment'}",
       "{'hypothesis_id': 'nda-20', 'hypothesis': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.', 'source_clause': '', 'hypothesis_label': 'not_mentioned'}",
       "{'hypothesis_id': 'nda-3', 'hypothesis': 'Confidential Information may include verbally conveyed information.', 'source_clause': '1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.', 'hypothesis_label': 'entailment'}",
       '{\'hypothesis_id\': \'nda-18\', \'hypothesis\': "Receiving Party shall not solicit some of Disclosing Party\'s representatives.", \'source_clause\': \'\', \'hypothesis_label\': \'not_mentioned\'}',
       "{'hypothesis_id': 'nda-7', 'hypothesis': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).', 'source_clause': '2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to:\\n2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:', 'hypothesis_label': 'entailment'}",
       "{'hypothesis_id': 'nda-17', 'hypothesis': 'Receiving Party may create a copy of some Confidential Information in some circumstances.', 'source_clause': 'The Recipient will not copy or reproduce the Confidential Information except as reasonably required for the purposes contemplated in this Agreement, and will ensure that any confidentiality or other proprietary rights notices on the Confidential Information are reproduced on all copies.', 'hypothesis_label': 'entailment'}",
       "{'hypothesis_id': 'nda-8', 'hypothesis': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.', 'source_clause': 'The Recipient may disclose the Confidential Information to the extent required by law, provided that, subject to and without any waiver of the privileges and immunities of UNHCR, the Recipient will give UNHCR sufficient prior notice of a request for the disclosure of the Confidential Information in order to allow UNHCR to have a reasonable opportunity to take protective measures or such other action as may be appropriate before any such disclosure is made.', 'hypothesis_label': 'entailment'}",
       "{'hypothesis_id': 'nda-13', 'hypothesis': 'Receiving Party may acquire information similar to Confidential Information from a third party.', 'source_clause': 'The Recipient shall not be precluded from disclosing the Confidential Information that is \\n(i) obtained by the Recipient without restriction from a third party who is not in breach of any obligation as to confidentiality to the owner of such Confidential Information or any other person, or ', 'hypothesis_label': 'entailment'}",
       '{\'hypothesis_id\': \'nda-5\', \'hypothesis\': "Receiving Party may share some Confidential Information with some of Receiving Party\'s employees.", \'source_clause\': \'2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to:\\n2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:\\n2.3.2.2 any entity over which the Party exercises effective managerial control; or,\', \'hypothesis_label\': \'entailment\'}',
       "{'hypothesis_id': 'nda-4', 'hypothesis': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.', 'source_clause': 'The Recipient shall use the Confidential Information solely for the purpose for which it was disclosed;', 'hypothesis_label': 'entailment'}"],
      dtype=object)

In [7]:
## Testing data versioning and access to registered datasets in MLRun
data_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_train_data:latest"
#data_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_test_data:20260405_1924"

# Fetch the item and immediately convert it to a Pandas DataFrame
df = mlrun.get_dataitem(data_uri).as_df()
#df.head()
print(df.head(1)['inference'][0])

[{'hypothesis': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information.", 'hypothesis_id': 'nda-11', 'hypothesis_label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.', 'hypothesis_id': 'nda-16', 'hypothesis_label': 'entailment', 'source_clause': '5. All Confidential Information in any form and any medium, including all copies thereof, disclosed to the Recipient shall be returned to UNHCR or destroyed: . (a) if a business relationship is not entered into with UNHCR on or before the date which is three (3) months after the date both Parties have signed the Agreement; or '}
 {'hypothesis': 'Agreement shall not grant Receiving Party any right to Confidential Information.', 'hypothesis_id': 'nda-15', 'hypothesis_label': 'entailment', 'source_clause': '4. Nothing in this Agreement is to be construed as granting the Recipient, by implication or otherwise, any right whatsoever with respect to the Confidential Information or part thereof.'}
 {'hypothesis': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.', 'hypothesis_id': 'nda-10', 'hypothesis_label': 'entailment', 'source_clause': '11. The Recipient shall not advertise or otherwise make public the fact that it has a confidential relationship with UNHCR, nor shall the Recipient, in any manner whatsoever use the name, emblem, or official seal of the United Nations or UNHCR, or any abbreviation of the name of the United Nations or UNHCR in connection with its business or otherwise.'}
 {'hypothesis': 'Confidential Information shall only include technical information.', 'hypothesis_id': 'nda-2', 'hypothesis_label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'All Confidential Information shall be expressly identified by the Disclosing Party.', 'hypothesis_id': 'nda-1', 'hypothesis_label': 'entailment', 'source_clause': '1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.'}
 {'hypothesis': 'Some obligations of Agreement may survive termination of Agreement.', 'hypothesis_id': 'nda-19', 'hypothesis_label': 'entailment', 'source_clause': 'Either Party may terminate the working relationship contemplated by this Agreement by providing written notice to the other, provided, however, that the obligations and restrictions hereunder regarding the Confidential Information shall remain effective following any such termination or any other termination or expiration of this Agreement.'}
 {'hypothesis': 'Receiving Party may independently develop information similar to Confidential Information.', 'hypothesis_id': 'nda-12', 'hypothesis_label': 'entailment', 'source_clause': 'The Recipient shall not be precluded from disclosing the Confidential Information that is . (iv) at any time is developed by the Recipient completely independently of any disclosures hereunder.'}
 {'hypothesis': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.', 'hypothesis_id': 'nda-20', 'hypothesis_label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'Confidential Information may include verbally conveyed information.', 'hypothesis_id': 'nda-3', 'hypothesis_label': 'entailment', 'source_clause': '1. “Confidential Information”, whenever used in this Agreement, shall mean any data, document, specification and other information or material, that is delivered or disclosed by UNHCR to the Recipient in any form whatsoever, whether orally, visually in writing or otherwise (including computerized form), and that, at the time of disclosure to the Recipient, is designated as confidential.'}
 {'hypothesis': "Receiving Party shall not solicit some of Disclosing Party's representatives.", 'hypothesis_id': 'nda-18', 'hypothesis_label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).', 'hypothesis_id': 'nda-7', 'hypothesis_label': 'entailment', 'source_clause': '2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to:. 2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:'}
 {'hypothesis': 'Receiving Party may create a copy of some Confidential Information in some circumstances.', 'hypothesis_id': 'nda-17', 'hypothesis_label': 'entailment', 'source_clause': 'The Recipient will not copy or reproduce the Confidential Information except as reasonably required for the purposes contemplated in this Agreement, and will ensure that any confidentiality or other proprietary rights notices on the Confidential Information are reproduced on all copies.'}
 {'hypothesis': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.', 'hypothesis_id': 'nda-8', 'hypothesis_label': 'entailment', 'source_clause': 'The Recipient may disclose the Confidential Information to the extent required by law, provided that, subject to and without any waiver of the privileges and immunities of UNHCR, the Recipient will give UNHCR sufficient prior notice of a request for the disclosure of the Confidential Information in order to allow UNHCR to have a reasonable opportunity to take protective measures or such other action as may be appropriate before any such disclosure is made.'}
 {'hypothesis': 'Receiving Party may acquire information similar to Confidential Information from a third party.', 'hypothesis_id': 'nda-13', 'hypothesis_label': 'entailment', 'source_clause': 'The Recipient shall not be precluded from disclosing the Confidential Information that is . (i) obtained by the Recipient without restriction from a third party who is not in breach of any obligation as to confidentiality to the owner of such Confidential Information or any other person, or '}
 {'hypothesis': "Receiving Party may share some Confidential Information with some of Receiving Party's employees.", 'hypothesis_id': 'nda-5', 'hypothesis_label': 'entailment', 'source_clause': '2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to:. 2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:. 2.3.2.2 any entity over which the Party exercises effective managerial control; or,'}
 {'hypothesis': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.', 'hypothesis_id': 'nda-4', 'hypothesis_label': 'entailment', 'source_clause': 'The Recipient shall use the Confidential Information solely for the purpose for which it was disclosed;'}]

In [8]:
data_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_test_data:latest"
data_pointer = mlrun.get_dataitem(data_uri)
print(data_pointer.url)

s3://legal-llama-data/processed_training/20260406_2110/raw-proc-process-raw/0/test_data.parquet

In [3]:
# This deletes all artifacts in the database
db = mlrun.get_run_db()
# Wipe all artifacts (including datasets) from this specific project
db.del_artifacts(project=project.metadata.name)

In [10]:
project.spec.get_code_path()

'../'