In [ ]:
# This is run from main working directory
import mlrun
mlrun.set_environment(api_path="http://localhost:30070")
project = mlrun.load_project(name="legalcontractextractor", context="../")
# print(project.to_yaml())

from dotenv import load_dotenv
load_dotenv()

import os
ENV = os.environ["ENV"]

# Run the workflow

In [7]:
from datetime import datetime
source_path = f"s3://{ENV}-mlops-bucket-haviv/data/raw"
version = datetime.now().strftime("%Y%m%d_%H%M")

output_path = f"s3://{ENV}-mlops-bucket-haviv/data/processed_training/"

In [12]:
# Train dataset
runobj = mlrun.run_function(
    "raw-proc",  # use the function name registered in the register_funcs.ipynb file
    inputs={"input_uri": f"{source_path}/train.parquet"},
    params={
        "label_column": "inference",
        "artifact_key": f"train_data",
        "version": version,
        "output_uri_path": "s3://legal-llama-data/processed_training",
    },
    local=True,
)

# Validation dataset
runobj = mlrun.run_function(
    "raw-proc",
    inputs={"input_uri": f"{source_path}/validation.parquet"},
    params={
        "label_column": "inference",
        "artifact_key": f"validation_data",
        "version": version,
        "output_uri_path": "s3://legal-llama-data/processed_training",
    },
    local=True,
)

# Test dataset
runobj = mlrun.run_function(
    "raw-proc",
    inputs={"input_uri": f"{source_path}/test.parquet"},
    params={
        "label_column": "inference",
        "artifact_key": f"test_data",
        "version": version,
        "output_uri_path": "s3://legal-llama-data/processed_training",
    },
    local=True,
)

> 2026-08-14 15:59:15,224 [info] Storing function: {"db":"http://localhost:30070","name":"raw-proc-process-raw","uid":"2b7d10dd5ee449189e592de4586fe4ee"}
s3://sand-mlops-bucket-haviv/data/raw/train.parquet processed and written to s3://legal-llama-data/processed_training/20260814_1551

> 2026-08-14 15:59:25,454 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}
> 2026-08-14 15:59:25,456 [info] Storing function: {"db":"http://localhost:30070","name":"raw-proc-process-raw","uid":"c212ce0ee84e40418d62ef43fad5a8ef"}
s3://sand-mlops-bucket-haviv/data/raw/validation.parquet processed and written to s3://legal-llama-data/processed_training/20260814_1551

> 2026-08-14 15:59:29,313 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}
> 2026-08-14 15:59:29,320 [info] Storing function: {"db":"http://localhost:30070","name":"raw-proc-process-raw","uid":"17d0da779dbc45e4a14fb4e3e25f45c9"}
s3://sand-mlops-bucket-haviv/data/raw/test.parquet processed and written to s3://legal-llama-data/processed_training/20260814_1551

> 2026-08-14 15:59:33,185 [info] Run execution finished: {"name":"raw-proc-process-raw","status":"completed"}

In [ ]:
# For kubeflow pipelines: not using during development because of ghost runs and caching issues..for another time
# from datetime import datetime

# run_obj = project.run(
#     name="evaluate_noTrain",
#     arguments={
#         "source_path": "s3://legal-llama-data/raw",
#         "version": datetime.now().strftime("%Y%m%d_%H%M")
#     },
#     local=True,   # Run the pipeline sequence locally
#     watch=True    # Print the progress to the console
# )

## Validation

In [16]:
from IPython.display import display

# Testing direct access to S3 data (underlying s3fs)
# data_uri = "s3://legal-llama-data/raw/test.parquet"
# df = mlrun.get_dataitem(data_uri).as_df() #this reads into a dataframe and only works if the file is a csv/parquet... jsonl does not work
# display(df.head(1))

data_uri = "store://datasets/legalcontractextractor/raw-proc-process-raw_test_data:latest"
data_pointer = mlrun.get_dataitem(data_uri)
print(data_pointer.url) # S3 path

s3://legal-llama-data/processed_training/20260814_1551/raw-proc-process-raw/0/test_data.parquet

In [17]:
# Testing data versioning and access to registered datasets in MLRun
data_uri = "store://datasets/legalcontractextractor/raw-proc-process-raw_test_data:latest"
#data_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_test_data:20260427_1945"

# Fetch the item and immediately convert it to a Pandas DataFrame
df = mlrun.get_dataitem(data_uri).as_df()
print(df.head(1)['inference'][0])

[{'hypothesis': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information.", 'hypothesis_id': 'nda-11', 'label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.', 'hypothesis_id': 'nda-16', 'label': 'entailment', 'source_clause': 'The Recipient shall immediately return and redeliver to the other all tangible material embodying the JEA Confidential Information provided hereunder and all notes, summaries, memoranda, drawings, manuals, records, excerpts or derivative information deriving there from and all other documents or materials ("Notes") (and all copies of any of the foregoing, including "copies" that have been converted to computerized media in the form of image, data or word processing files either manually or by image capture) based on or including any JEA Confidential Information, in whatever form of storage or retrieval, upon the earlier of -. I. the completion or termination of the dealings between the parties contemplated hereunder; or. II. the termination of this Agreement; or'}
 {'hypothesis': 'Agreement shall not grant Receiving Party any right to Confidential Information.', 'hypothesis_id': 'nda-15', 'label': 'entailment', 'source_clause': 'No other right or license, whether expressed or implied, in the Confidential Information is granted to the Parties hereunder. '}
 {'hypothesis': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.', 'hypothesis_id': 'nda-10', 'label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'Confidential Information shall only include technical information.', 'hypothesis_id': 'nda-2', 'label': 'contradiction', 'source_clause': 'For purposes of this Agreement, "Confidential Information" means any data or information that is proprietary to the Parties and not generally known to the public, whether in tangible or intangible form, whenever and however disclosed, including but not limited to:. g. any Copyright application code, source code, technical design (not released for open use), trade secret, scientific or technical information, invention, design, process, procedure, formula, improvement, technology or method;'}
 {'hypothesis': 'All Confidential Information shall be expressly identified by the Disclosing Party.', 'hypothesis_id': 'nda-1', 'label': 'contradiction', 'source_clause': 'For purposes of this Agreement, "Confidential Information" means any data or information that is proprietary to the Parties and not generally known to the public, whether in tangible or intangible form, whenever and however disclosed, including but not limited to:'}
 {'hypothesis': 'Some obligations of Agreement may survive termination of Agreement.', 'hypothesis_id': 'nda-19', 'label': 'entailment', 'source_clause': "b. Notwithstanding the foregoing, the parties' duty to hold in confidence Confidential Information that was disclosed during term shall remain in effect indefinitely."}
 {'hypothesis': 'Receiving Party may independently develop information similar to Confidential Information.', 'hypothesis_id': 'nda-12', 'label': 'entailment', 'source_clause': "The obligations and restrictions imposed by this Agreement will not apply to any information that:. d. was independently developed by the Recipient without use of the Discloser's Confidential Information; or"}
 {'hypothesis': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.', 'hypothesis_id': 'nda-20', 'label': 'entailment', 'source_clause': 'e. Return of Information. on a Party\'s request, the other Party shall return all Confidential Information of the requesting Party, except for that portion of such Confidential Information that may be found in analyses prepared by, or for, the returning Party (collectively, "Analyses"), and the returning Party and its Representatives shall not retain any copies of such Confidential Information except the returning Party may retain one copy of the Confidential Information as needed to comply with applicable law and/or returning Party\'s record retention policies. '}
 {'hypothesis': 'Confidential Information may include verbally conveyed information.', 'hypothesis_id': 'nda-3', 'label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': "Receiving Party shall not solicit some of Disclosing Party's representatives.", 'hypothesis_id': 'nda-18', 'label': 'not_mentioned', 'source_clause': ''}
 {'hypothesis': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).', 'hypothesis_id': 'nda-7', 'label': 'entailment', 'source_clause': 'The Parties will:. a. limit disclosure of any Confidential Information to its directors, officers, employees, agents or representatives (collectively "Representatives") who have a need to know such Confidential Information in connection with the Transaction, and only for that purpose;'}
 {'hypothesis': 'Receiving Party may create a copy of some Confidential Information in some circumstances.', 'hypothesis_id': 'nda-17', 'label': 'entailment', 'source_clause': 'e. Return of Information. on a Party\'s request, the other Party shall return all Confidential Information of the requesting Party, except for that portion of such Confidential Information that may be found in analyses prepared by, or for, the returning Party (collectively, "Analyses"), and the returning Party and its Representatives shall not retain any copies of such Confidential Information except the returning Party may retain one copy of the Confidential Information as needed to comply with applicable law and/or returning Party\'s record retention policies. '}
 {'hypothesis': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.', 'hypothesis_id': 'nda-8', 'label': 'entailment', 'source_clause': 'a. The Recipient may disclose Confidential Information pursuant to any governmental, judicial, or administrative order, subpoena, discovery request, regulatory request or similar method, provided that the Recipient promptly notifies, to the extent practicable.'}
 {'hypothesis': 'Receiving Party may acquire information similar to Confidential Information from a third party.', 'hypothesis_id': 'nda-13', 'label': 'entailment', 'source_clause': "The obligations and restrictions imposed by this Agreement will not apply to any information that:. c. was received by the Recipient without breach of this Agreement from a third party without restriction as to the use and disclosure of the Discloser's Confidential Information; or,"}
 {'hypothesis': "Receiving Party may share some Confidential Information with some of Receiving Party's employees.", 'hypothesis_id': 'nda-5', 'label': 'entailment', 'source_clause': 'The Parties will:. a. limit disclosure of any Confidential Information to its directors, officers, employees, agents or representatives (collectively "Representatives") who have a need to know such Confidential Information in connection with the Transaction, and only for that purpose;. The Receiving Party agrees to use the same degree of protection it uses for its own trade secret information, and in no event less than reasonable efforts, to prevent and protect the Confidential Information, or any part thereof, from disclosure to any person other than the Receiving Party\'s employees having a need for disclosure in connection with the Receiving Party\'s authorized use of the Confidential Information.'}
 {'hypothesis': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.', 'hypothesis_id': 'nda-4', 'label': 'entailment', 'source_clause': 'The Parties agree to use the Confidential Information solely in connection with the Transaction and not for any purpose other than as authorized by this Agreement without the prior written consent of an authorized representative of the Parties. . The Parties agree to ensure that all copyright products, such as source codes, system design data/architecture, and other proprietary information, disclosed during the engagement is protected from any misuse, alteration, modification, sharing, or transfer to any party without express permission of the Discloser. . Such data is provided for the sole use of the Parties, and limited for the use under this agreement.. The Receiving Party agrees not to use the Confidential Information in any way, or to manufacture or test any product embodying Confidential Information, except for the purpose set forth above.'}]

In [ ]:
"""
# I blame mlrun for this weird behaviour, instead of the URI on the UI with the ://files path segment, it uses ://datasets
# Now that we are not using 
artifact_uri = "store://datasets/finetune-legal-extractor/raw-proc-process-raw_test_data:latest"

data_item = mlrun.get_dataitem(artifact_uri)
s3_path = data_item.url
print(s3_path) 

import pandas as pd
import io

raw_bytes = data_item.get()
df = pd.read_json(io.BytesIO(raw_bytes), orient="records", lines=True)

inferences = df.head(1)['inference'][0]
for i in inferences:
    print(i)
"""

In [14]:
artifact = project.get_artifact(key="raw-proc-process-raw_validation_data", tag="20260814_1551") # use the db-key not key
# this wont work project.get_artifact(key="train_data")

print(artifact.get_store_url())
print(artifact.target_path) # points to the source path of the latest version of the artifact
print(artifact.db_key)
print(artifact.key)

store://datasets/legalcontractextractor/raw-proc-process-raw_validation_data#0:20260814_1551@c212ce0ee84e40418d62ef43fad5a8ef^a85f5e46a24a633a38110fe912b3c5759647623e
s3://legal-llama-data/processed_training/20260814_1551/raw-proc-process-raw/0/validation_data.parquet
raw-proc-process-raw_validation_data
validation_data

In [15]:
# all datasets
artifacts = project.list_artifacts()
datasets = [artifact for artifact in artifacts if artifact['kind'] == "dataset"]
for i in datasets:
    print(i['metadata']['key'], i['metadata']['tag'])

test_data latest
test_data 20260814_1551
validation_data latest
validation_data 20260814_1551
train_data latest
train_data 20260814_1551
train_data None

# Deleting artifacts directly

In [ ]:
adsasd

In [ ]:
# The only way to properly delete a data artifact and its historical versions
import os 

artifact = project.get_artifact(key="raw-proc-process-raw_train_data")
project.delete_artifact(artifact, 
                        deletion_strategy=mlrun.common.schemas.artifact.ArtifactsDeletionStrategies.data_force,
                        secrets={
                            "AWS_ACCESS_KEY_ID": os.environ['AWS_ACCESS_KEY_ID'],
                            "AWS_SECRET_ACCESS_KEY": os.environ['AWS_SECRET_ACCESS_KEY']
                            }
                        )

In [ ]:
# This deletes all artifacts in the database
db = mlrun.get_run_db()
db.del_artifacts(project=project.metadata.name)

print("all artifacts wiped from " + project.metadata.name)

In [ ]:
project.spec.get_code_path()